apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/azunymous/andromeda/aggregator/platform/base
  - ingress.yaml
configMapGenerator:
  - name: aggregator-config
    files:
      - application-agg.yaml
patchesStrategicMerge:
  - deployment-image.yaml
  - deployment-config.yaml