apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/azunymous/andromeda/web/platform/base
  - ingress.yaml

patchesStrategicMerge:
  - deployment-image.yaml
  - deployment-config.yaml

configMapGenerator:
  - name: web-config
    files:
      - config.js