apiVersion: skaffold/v1
kind: Config
metadata:
  name: alice
build:
  artifacts:
  - image: gcr.io/alice-ws/test/alice
    context: api
  - image: gcr.io/alice-ws/test/alice-web
    context: web
    docker:
      dockerfile: development.Dockerfile
deploy:
  kustomize:
    path: ./platform/development
profiles:
- name: test
  build:
    artifacts:
    - image: gcr.io/alice-ws/test/alice
      context: api
    - image: gcr.io/alice-ws/test/alice-ft
      context: testing/apitest
  deploy:
    kustomize:
      path: ./platform/testing
- name: api
  build:
    artifacts:
    - image: gcr.io/alice-ws/test/alice
      context: api
  deploy:
    kustomize:
      path: ./api/platform/development
- name: web
  build:
    artifacts:
    - image: gcr.io/alice-ws/test/alice-web
      context: web
  deploy:
    kustomize:
      path: ./web/platform/development
- name: minio-cluster
  deploy:
    kustomize:
      path: ./platform/dependencies/minio/development-distributed
- name: redis-cluster
  deploy:
    kustomize:
      path: ./platform/dependencies/redis/distributed
- name: andromeda
  deploy:
    kustomize:
      path: ./platform/andromeda
- name: production
  build:
    artifacts:
      - image: gcr.io/alice-ws/production/alice
        context: api
      - image: gcr.io/alice-ws/production/alice-web
        context: web
  deploy:
    kustomize:
      path: ./platform/production
