apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: alice
          image: alice:0.0.1
          volumeMounts:
            - name: config
              mountPath: /config/
      volumes:
        - name: config
          configMap:
            name: alice-config