namespace: alice-web
commonLabels:
  variant: development
commonAnnotations:
  note: This is a development environment
resources:
  - ../base
patchesStrategicMerge:
  - deployment_replicas.yaml
  - deployment_spec.yaml