apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice
spec:
  template:
    spec:
      containers:
        - name: alice
          image:  gcr.io/alice-ws/test/alice:0.0.1
          volumeMounts:
            - name: config-volume
              mountPath: /config/
      volumes:
        - name: config-volume
          configMap:
            name: alice-config
