apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alice-testing
resources:
  - ../base
patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_spec.yaml
- deployment_minio_secrets.yaml
configMapGenerator:
  - name: alice-config
    files:
      - config.yaml