apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: redis
resources:
  - statefulset.yaml
  - service.yaml
configMapGenerator:
  - name: redis-config
    files:
      - redis.conf