apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: minio
  variant: development
namespace: minio
resources:
  - ../base

patchesStrategicMerge:
  - statefulset_env.yaml
  - statefulset_probes.yaml
secretGenerator:
  - name: minio-access
    envs:
      - env.development.local