apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alice-production
commonLabels:
  variant: production
resources:
  - ../base
  - namespace.yaml
  - ingress.yaml
patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_spec.yaml
- deployment_minio_secrets.yaml
configMapGenerator:
  - name: alice-config
    files:
      - config.yaml
secretGenerator:
  - name: minio-access
    envs:
      - env.production.local