apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: minio
  variant: development-distributed
namespace: minio
resources:
  - ../development
  - service.yaml

patchesStrategicMerge:
  - statefulset_distributed.yaml
  - headless_service.yaml
  - ingress.yaml