apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alice
  template:
    metadata:
      labels:
        app: alice
    spec:
      containers:
        - name: alice
          image: alice:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: environment
              value: "dev"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080