apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: minio
  variant: development
namespace: alice-development
resources:
  - ../base
  - ingress.yaml
patchesStrategicMerge:
  - statefulset_env.yaml
  - statefulset_probes.yaml
secretGenerator:
  - name: minio-keys
    envs:
      - env.development.local